version: '3.8'

services:
  # Service MongoDB
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-network

  # Service Server (Backend)
  server:
    build: ./server
    container_name: server
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
    networks:
      - mern-network

  # Service Client (Frontend)
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - mern-network

# Réseaux
networks:
  mern-network:
    driver: bridge

